version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - proxchat_data:/var/lib/mysql:/data

  backend:
    image: proxchat-backend
    environment:
      DOCKER_MODE: "true"
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      OPENAI_KEY: ${OPENAI_KEY}
    volumes:
      - ./logs:/app/data
    depends_on:
      - db
    ports:
      - "6969:6969"

  frontend:
    image: proxchat-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  proxchat_data:
